on:
  push:
    tags:
      - '*'

name: Release Builds
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: DUMP ENV
        env:
          VAR: ${{ github.event }}
        run: |
          echo "dot ${{ toJson(github.event) }}"
          echo "nodot ${{ toJson($VAR) }}"
